# Generated by Django 3.0.8 on 2020-07-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('query', models.TextField()),
                ('resource_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
